FROM node:18.15-alpine3.17 AS build
WORKDIR /app

COPY ./humblib .
RUN npm install
RUN npm run build
FROM nginx:alpine
COPY ./humblib/nginx/conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/humblib/ /usr/share/nginx/html 
