FROM node:16-alpine
WORKDIR /app

COPY ./humblib .
RUN npm install
RUN npm run build
FROM nginx:alpine
COPY ./humblib/dist/humblib /usr/share/nginx/html
COPY ./humblib/node_modules /use/share/nginx/html/node_modules
COPY ./humblib/nginx.conf /etc/nginx
EXPOSE 8080
