version: "3.9"
name: humblib-dev
services:
  humblib-front:
    build:
      dockerfile: Dockerfile.dev
      context: ./
      args:
        - port=4200
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "./:/app"
      - "/app/node_modules/"
    command: sh -c "npm install && npm install -g @angular/cli@latest && ng serve --host 0.0.0.0 "
